services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - ./request.json:/etc/app/request.json
    ports:
      - "8080:8080"
    environment:
      - INTERVAL_MIN_SEC=4
      - INTERVAL_MAX_SEC=6
      - TARGET_URL=https://catfact.ninja/fact
      - HTTP_METHOD=POST
      - HTTP_HEADERS=Content-Type:application/json
